git clone git@github.com:company/*.git 
git clone https://github.com/Tuhinshubhra/RED_HAWK
git clone https://github.com/sqlmapproject/sqlmap
git clone https://github.com/bibortone/D-Tech
git clone https://github.com/m4ll0k/Infoga
git clone https://github.com/s0md3v/ReconDog
curl  -O https://raw.githubusercontent.com/Gameye98/Gameye98.github.io/master/scripts/androzenmap.sh
git  clone https://github.com/s0md3v/sqlmate
git  clone https://github.com/Gameye98/AstraNmap
https://github.com/Hornegam/Python_Pentest/blob/master/BruteForce
git  clone https://github.com/evait-security/weeman
git  clone https://github.com/Cvar1984/Easymap
git  clone https://github.com/evait-security/weeman
git  clone https://github.com/Ubaii/Xshell
git  clone https://github.com/UndeadSec/EvilURL
git  clone https://github.com/s0md3v/Striker
git  clone https://github.com/stamparm/DSSS
git  clone https://github.com/the-robot/sqliv
git  clone http://www.github.com/Cvar1984/sqlscan
git  clone https://github.com/swisskyrepo/Wordpresscan
git  clone https://github.com/threat9/routersploit
git  clone https://github.com/jseidl/GoldenEye
git  clone https://github.com/baraalmasri/xerxes
git  clone https://github.com/Hydra7/Planetwork-DDOS
git  clone https://github.com/Gameye98/Black-Hydra
git  clone https://github.com/Mebus/cupp
git  clone https://github.com/LOoLzeC/ASU
git  clone https://github.com/s0md3v/Hash-Buster
git  clone https://github.com/Slayeri4/instahack
git  clone https://github.com/geovedi/indonesian-wordlist
curl  -O https://raw.githubusercontent.com/Gameye98/Gameye98.github.io/master/scripts/facebook3.py
curl  -O https://raw.githubusercontent.com/Gameye98/Gameye98.github.io/master/wordlist/password.txt
git  clone https://github.com/The404Hacking/websploit
git  clone https://github.com/commixproject/commix
git  clone https://github.com/Screetsec/Brutal
git  clone https://github.com/4w4k3/KnockMail
git  clone https://github.com/Cvar1984/Hac
git  clone https://github.com/floriankunushevci/rang3r
git  clone https://github.com/LOoLzeC/social-engineering
git  clone https://github.com/LOoLzeC/SH33LL
git  clone https://github.com/Cvar1984/SpiderBot
git  clone https://github.com/themastersunil/ngrok
git  clone https://github.com/st42/termux-sudo
git  clone https://github.com/Neo-Oli/termux-ubuntu
git  clone https://github.com/Hax4us/Nethunter-In-Termux
git  clone https://github.com/jothatron/blackbox
git  clone https://github.com/Moham3dRiahi/XAttacker
git  clone https://github.com/LOoLzeC/Evil-create-framework
git  clone https://github.com/UndeadSec/SocialFish
git  clone https://github.com/Cvar1984/Ecode
git  clone https://github.com/s0md3v/XSStrike
git  clone https://github.com/s0md3v/Breacher
git  clone https://github.com/BagazMukti/Termux-Styling-Shell-Script
git  clone https://github.com/kuburan/txtool
git  clone https://github.com/Cvar1984/PassGen
git  clone https://github.com/Gameye98/OWScan
git  clone https://github.com/Gameye98/santet-online
git  clone https://github.com/Gameye98/SpazSMS
git  clone https://github.com/CiKu370/hasher
git  clone https://github.com/CiKu370/hash-generator
git  clone https://github.com/CiKu370/ko-dork
git  clone https://github.com/Smaash/snitch
git  clone https://github.com/milio48/nk26
git  clone https://github.com/joker25000/Devploit
git  clone https://github.com/galauerscrew/hasherdotid
git  clone https://github.com/HA71/Namechk
git  clone https://github.com/albertoanggi/xl-py
git  clone https://github.com/Gameye98/FaDe
git  clone https://github.com/Gameye98/GINF
git  clone https://github.com/CiKu370/AUXILE
git  clone https://github.com/Gameye98/inther
git  clone https://github.com/Gameye98/FMBrute
git  clone https://github.com/indosecid/gps_tracking
git  clone https://github.com/RUB-NDS/PRET
git  clone https://github.com/m4ll0k/Atlas
git  clone https://github.com/Gameye98/FBBrute
git  clone https://github.com/karjok/fim
git  clone https://github.com/Jishu-Epic/RShell
git  clone https://github.com/Jishu-Epic/TermPyter
git  clone https://github.com/maxteroit/MaxSubdoFinder
git  clone https://github.com/thewhiteh4t/pwnedOrNot
git  clone https://github.com/T4P4N/Mac-Lookup
git  clone https://github.com/Gameye98/Katak
git  clone https://github.com/GitHackTools/BillCipher
git  clone https://github.com/Gameye98/vbug
git  clone https://github.com/sandalpenyok/kojawafft
apt  install root-repo ettercap
git  clone https://github.com/Gameye98/ccgen
git  clone https://github.com/Gameye98/ddcrypt
git  clone https://github.com/darkoperator/dnsrecon
git  clone https://github.com/htr-tech/zphisher
git  clone https://github.com/Lexiie/Termux-Apktool
git  clone https://github.com/derv82/wifite
git  clone https://github.com/sdrausty/TermuxArch
git  clone https://github.com/foospidy/DbDat
git  clone https://github.com/codingo/NoSQLMap
git  clone https://github.com/iriscouch/audit_couchdb
git  clone https://github.com/wifiphisher/wifiphisher
git  clone https://github.com/sherlock-project/sherlock
git  clone https://github.com/ExpertAnonymous/PhoneInfoga
git  clone https://github.com/guruku/BTC-to-IDR-checker
git  clone https://github.com/Anon-Exploiter/SiteBroker
git  clone https://github.com/verluchie/dost-attack
git  clone https://github.com/extremecoders-re/pyinstxtractor
git  clone https://github.com/dscharrer/innoextract
git  clone https://github.com/CISOfy/lynis
git  clone https://github.com/Magentron/chkrootkit
git  clone https://github.com/r00tmars/XPL-SEARCH
git  clone https://github.com/Manisso/Xadmin
git  clone https://github.com/lightos/credmap
git  clone https://github.com/bhikandeshmukh/MapEye
git  clone https://github.com/AngelSecurityTeam/GatheTOOL
git  clone https://github.com/sslab-gatech/avpass
git  clone https://github.com/ReFirmLabs/binwalk
git  clone https://github.com/JustaHackers/street_car
git  clone https://github.com/JustAHackers/flappy_bird
git  clone https://github.com/JustAHackers/typing-speed-test
git  clone https://github.com/TheMagizz/Darkvip
git  clone https://github.com/gameye98/Lazymux
git  clone https://github.com/Rajnudusad/Tool-X
git  clone https://github.com/kancotdiq/ipcs
git  clone https://github.com/Manisso/fsociety
git  clone https://github.com/Night420/Termux-Fix
git  clone https://github.com/googleinurl/scanner-inurl
git  clone https://github.com/UltimateHackers/Hash-Buster
git  clone https://github.com/threat9/routersploit
git  clone https://github.com/samay827/samayphish2
git  clone https://github.com/Tuhinshubrha/RED_HAWK
git  clone https://github.com/issamelgerkh/userrecon.git
git  clone https://github.com/pembriahmad/DDOS
git  clone https://github.com/TSMaitry/VirusX
git  clone https://github.com/CyberXCodder/XerXes.git
git  clone https://github.com/termuxprofessor/insunfollow
git  clone https://github.com/th3unkn0r/osi.ig
git  clone https://github.com/techchipnet/CamPhish
git  clone https://github.com/DarkSecDeveloper/HiddenEye.git
git  clone https://github.com/Datalux/Osintgram
git  clone https://github.com/lulz3xploit/LittleBrother
git  clone https://github.com/FluxionNetwork/fluxion
git  clone https://github.com/arismelachroinos/lscript
echo -e "\e[32m[+] Script created by P.\e[0m";
